[build]
  command = "npm run start" # или команда, которую вы используете для сборки проекта

[[redirects]]
  from = "/*"
  to = "/root/:splat" # это указывает, что все запросы перенаправляются на файлы в папке "root"
  status = 200

[[headers]]
  for = "/root/*" # указываем, что это для файлов в папке "root"
    [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate" # настройки кэширования
