[build]
  base = "root" # Указываем базовую директорию для сборки

  # Настроим команды сборки (если они нужны)
  command = "npm run build" # Замените на вашу команду сборки, если необходимо

[build.environment]
  TELEGRAM_BOT_TOKEN = "6774167185:AAFfpIXcx2zdDkjQocnsdwTTWPHsnCm0jBE" # Установите переменную среды TELEGRAM_BOT_TOKEN

[[redirects]] # Настройка перенаправления, если нужно
  from = "/*"
  to = "/root/:splat"
  status = 200

[context.production.environment]
  NODE_ENV = "production" # Устанавливаем NODE_ENV в production для окружения production

[context.split1.environment]
  NODE_ENV = "production" # Устанавливаем NODE_ENV в production для других окружений, если нужно

# Дополнительные настройки могут быть добавлены согласно вашим требованиям
