# Настройки сборки и развертывания на Netlify
[build]
  command = "npm run build" # Команда для сборки вашего проекта
  publish = "root"          # Каталог, содержащий файлы, которые вы хотите развернуть
